version: "3.7"

services:
  
  uuid-api:
    ports:
      - "2222:2222"
    links:
      - bcrf-mysql
    volumes:
      # Mount the VERSION file and BUILD file
      - "../VERSION:/usr/src/app/VERSION"
      - "../BUILD:/usr/src/app/BUILD"
      # Mount the source code to container
      - "../src:/usr/src/app/src"
  
   # Only used by local development
  bcrf-mysql:
    platform: linux/x86_64
    build: ./bcrf-mysql
    # Build the image with name and tag
    image: mysql:1.1
    hostname: bcrf-mysql
    container_name: bcrf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd1
      MYSQL_USER: uuid-user
      MYSQL_PASSWORD: St1nkyF33t
      MYSQL_DATABASE: bcrf_uuid
     # Use the same port mapping for dev and prod
    ports:
      - "3306:3306"
    networks:
      - elastic
    volumes:
      - bcrf-mysql:/var/lib/mysql
      - bcrf-mysql-config:/etc/mysql
volumes:
  bcrf-mysql:
  bcrf-mysql-config:
